---
title: "CV"
description: |
---

## [Click Here](Samantha_Kuglen_Resume.pdf) to view a PDF of my Resume.

### [Education]{.ul}

University of California, Santa Barbara (UCSB) \| Bren School of Environmental Science & Management

-   Master of Environmental Science Management with a Specialization in Conservation Planning and Coastal Marine Resources Management

University of California, San Diego (UCSD)

-   Bachelor of Science in Marine Biology and Minor in Environmental Studies

### [Professional Experience Overview]{.ul}

-   Graduate Student TA -- UCSB Environmental Studies Department

-   Watershed Stewards Program (WSP) -- Americorps, National Park Service

-   Data Management Assistant - Scripps Institution of Oceanography

-   Research Assistant -- NOAA Southwest Fisheries Science Center

-   Marine Biology & Ocean Operations (MBOO) Intern -- City of San Diego

### [Awards]{.ul}

-   Biological Sciences Undergraduate Excellence in Teaching Award 2018-2019

### [Outreach and Involvement]{.ul}

-   Clinton Global Initiative University (CGI U) Conference 2018
-   Alternative Breaks at UC San Diego
